### PR TITLE
Update SickRage to latest version

### PR DESCRIPTION
**Pull request by labrys**
@josh4trunks Please take a look at this before merging as I'm not running freenas and only passingly familiar with it.  This updates SickRage to the latest version, makes python 2.7 required, and removes Cheetah as a dependency.  Please let me know if you see anything I missed.  Also should the PORTREVISION change in the makefile?  If it's supposed to represent the SickRage release that would be 4.2.0

### CODE REVIEW

**Comment by josh4trunks** [comment]
thanks! I read the news yesterday and merge these changes in as soon as I have a chance.

I have just been bumping the port revision when I produce a new build, but not necessarily coinciding it with the actual releases since SickRage auto-updates itself.

**Comment by labrys** [comment]
Kind of figured that but wasn't too sure.  Also @miigotu wanted to know if there was a way to add Python 2.7.10.

**Comment by josh4trunks** [comment]
not through the port, just depends on what's in the ports tree I build the plugin with. but yes, I'll make sure it uses 2.7.10

**Comment by labrys** [comment]
I appreciate it!

**Comment by miigotu** [comment]
:+1:

**Comment by labrys** [comment]
@josh4trunks I created a Freenas VM to test this... so how would I go about installing the freenas-plugins... i assume I could just git clone the PR and follow the readme.md and finally install SickRage from the webui.  Anything I'm missing? Or am I way offbase?

**Comment by josh4trunks** [comment]
it's not very easy to build a plugin (PBI) for freenas at the moment. here's a relevant post you can follow.
https://forums.freenas.org/index.php?threads/more-plugins.14626/page-2#post-175364

**Comment by labrys** [comment]
thanks for the quick response... ill give it a try and see what happens :)

**Comment by labrys** [comment]
Assuming the PBI builds successfully, what would the next step be?

**Comment by josh4trunks** [comment]
you upload it on your freenas' plugins tab.

**Comment by labrys** [comment]
I meant to get it out to people, is there a repository that I should push it to?  Sorry for the noob questions, this is my first experience with Freenas.

**Comment by labrys** [comment]
I'm willing to RTFM, but right now I wouldn't even know where to look and my google-fu has failed me so far... granted I'm really tired so thats something :)

**Comment by labrys** [comment]
Ok looks like maybe Appcafe is where I would post it... correct?

**Comment by josh4trunks** [comment]
not anymore. I maintain a local repo that is synced to the official freenas repos.

**Comment by labrys** [comment]
Ok so build PBI -> submit to you? Sorry brain too fuzzy I think I'll hit this after I've slept I cant even keep my eyes open right now :)

**Comment by josh4trunks** [comment]
if your main goal is getting this changed to the new repo, I can do that as soon as I find some time. maybe this weekend.

this is also discussed here in case you want to join the conversation.
https://forums.freenas.org/index.php?threads/new-sickrage-repo.39368/

**Comment by labrys** [comment]
Cool yeah thats pretty much my goal I had someone asking me if it worked and how to install it and I figured if I couldnt answer that myself I wouldnt be much good to them...

**Comment by labrys** [comment]
And once again thanks so much for your patience and help

**Comment by labrys** [comment]
I think I'll read the conversation you just posted and then hit the sack

**Comment by josh4trunks** [comment]
hey @labrys @miigotu 
Was the source update/initial versioning function updated for the new repo URL? I'm getting this error in SickRage built with the new repo.
screenshot from 2015-11-28 15-26-04

Clicking "Update Now" just brings me back the same error after this runs.
screenshot from 2015-11-28 15-30-05

Also was there a particular need for python 2.7.10? I currently have this built with 2.7.9 but can go through the effort of updating this dependency if it actually mattered. Thanks

**Comment by labrys** [comment]
If you're referring to the PORTREVISION field, that wasn't changed as I wasn't sure how that should update.  If the PORTREVISION should be syncing to our release that should be changed to 
4.2.0.3 for the minor release updated here.  If that requires a rebuild, I can update this package to 4.2.0.6, our current release, before it gets rebuilt.

As for updates through github, that should work with no difference, except the URL which has been updated both in SickRage and in this package.  If this is being installed as an update, its possible the config.ini file still has the old repo's url and that may be causing the issue.

As for python 2.7.9 vs 2.7.10, while I'm not specifically aware of any incompatibilities, we do all our development, testing, and troubleshooting on 2.7.10. Our goal is to move to Python 3 while retaining backwards compatibility with 2.7.10.

**Comment by miigotu** [comment]
2.7.9 will suffice @josh4trunks since SNI support for the ssl module built into python was added in 2.7.9 which eliminates the need for pyopenSSL

About that updating thing, it seems that your package thinks it is installed from source and not git?

**Comment by josh4trunks** [comment]
It was a fresh install where the screenshots were from. sickrage's process has ownership of it's source directory but doesn't seem to be able pull the latest version, and know what version it's on. (which is how this used to work.)

We'll need to get this working before I post the update to the repo so auto-updates through sickrage work moving forward.

**Comment by josh4trunks** [comment]
it is installed from source.

**Comment by miigotu** [comment]
I will look into that. I have never installed from source so Im not sure how it works yet. Will get right on it tonight.

**Comment by josh4trunks** [comment]
I remember I read into it before when I copied the code over to the htpc-manager project. it basically grabs the latest then stores the version number in a text file (I believe). It then uses some function from github to grab diffs between version numbers (again if I remember correctly)

**Comment by miigotu** [comment]
I think I have this fixed, will be merging to develop tonight. As soon as I have tested a few things in develop we will merge to master (maybe tomorrow) and tag the release.

Should we then PR here with the new tag number then or can you take care of that?

**Comment by josh4trunks** [comment]
I can take care of it once it's in master. thanks for taking a look!

**Comment by miigotu** [comment]
Merged to master, now @ tag v4.2.1.0

**Comment by josh4trunks** [comment]
Works! I'll post the update to the plugin today and it'll be in the official FreeNAS plugins repo tomorrow.

Thanks for the quick work

**Comment by miigotu** [comment]
Thanks.

**Pull request merged**
